<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.1 on darwin)" generated="20210211 18:24:48.750" rpa="false">
<suite id="s1" name="Test" source="/Users/cecillian/Documents/robotF/test/test.robot">
<test id="s1-t1" name="search gundam">
<kw name="Search Gundam">
<msg timestamp="20210211 18:24:48.824" level="FAIL">No keyword with name 'Search Gundam' found.</msg>
<status status="FAIL" starttime="20210211 18:24:48.824" endtime="20210211 18:24:48.824"></status>
</kw>
<status status="FAIL" starttime="20210211 18:24:48.822" endtime="20210211 18:24:48.824" critical="yes">No keyword with name 'Search Gundam' found.</status>
</test>
<status status="FAIL" starttime="20210211 18:24:48.754" endtime="20210211 18:24:48.825"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210211 18:24:48.815" level="ERROR">Error in file '/Users/cecillian/Documents/robotF/test/test.robot' on line 2: Importing test library 'selenium2library' failed: ModuleNotFoundError: No module named 'selenium2library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/cecillian/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages</msg>
</errors>
</robot>
